<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lacuna.Sign</RootNamespace>
    <UserSecretsId>ef2f2edc-8379-439f-a41f-16807c6c4e24</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PdfStamp.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PdfStamp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Lacuna.Pki" Version="2.21.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.0" />
    <PackageReference Include="PDFsharp" Version="6.2.3" />
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
  </ItemGroup>

</Project>
